<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfTwig\View\Service\ViewTwigRendererFactory' => __DIR__ . '/src/ZfTwig/View/Service/ViewTwigRendererFactory.php',
    'ZfTwig\View\Service\ViewTwigStrategyFactory' => __DIR__ . '/src/ZfTwig/View/Service/ViewTwigStrategyFactory.php',
    'ZfTwig\View\Strategy\TwigRendererStrategy'   => __DIR__ . '/src/ZfTwig/View/Strategy/TwigRendererStrategy.php',
    'ZfTwig\View\Renderer'                        => __DIR__ . '/src/ZfTwig/View/Renderer.php',
    'ZfTwig\View\HelperFunction'                  => __DIR__ . '/src/ZfTwig/View/HelperFunction.php',
    'ZfTwig\View\Extension'                       => __DIR__ . '/src/ZfTwig/View/Extension.php',
    'ZfTwig\View\Extension\Render\RenderNode'     => __DIR__ . '/src/ZfTwig/View/Extension/Render/RenderNode.php',
    'ZfTwig\View\Extension\Render\TokenParser'    => __DIR__ . '/src/ZfTwig/View/Extension/Render/TokenParser.php',
    'ZfTwig\View\Extension\Trigger\RenderNode'    => __DIR__ . '/src/ZfTwig/View/Extension/Trigger/RenderNode.php',
    'ZfTwig\View\Extension\Trigger\TokenParser'   => __DIR__ . '/src/ZfTwig/View/Extension/Trigger/TokenParser.php',
    'ZfTwig\View\Resolver'                        => __DIR__ . '/src/ZfTwig/View/Resolver.php',
    'ZeTwig\View\Exception\TemplateException'     => __DIR__ . '/src/ZfTwig/View/Exception/TemplateException.php',
    'ZfTwig\View\Environment'                     => __DIR__ . '/src/ZfTwig/View/Environment.php',
    'ZfTwig\Module'                               => __DIR__ . '/Module.php',
);